package com.photogram.feature.privacy

internal data class PrivacyStrings(
    val title: String,
    val currentStatus: String,
    val privateProfile: String,
    val onlyYouMode: String,
    val membersMode: String,
    val publicAlbumsSuffix: String,
    val privatePhotosSuffix: String,
    val levelDescription: String,
    val stepProfile: String,
    val stepAlbums: String,
    val stepPhotos: String,
    val hierarchyHint: String,
    val sectionProfileMode: String,
    val soloTitle: String,
    val soloDesc: String,
    val membersTitle: String,
    val membersDesc: String,
    val defaultBadge: String,
    val warningText: String,
    val sectionWhatCanSee: String,
    val photoAndName: String,
    val alwaysVisibleFor: String,
    val always: String,
    val publicPhotos: String,
    val stats: String,
    val sectionAlbums: String,
    val whoCanInvite: String,
    val approveBeforeJoining: String,
    val approveDesc: String,
    val sectionAlbumSummary: String,
    val albumPrivate: String,
    val albumWithLink: String,
    val albumPublic: String,
    val albumUnit: String,
    val albumUnitPlural: String,
    val managePrivacy: String,
    val saveChanges: String,
) {
    companion object {
        fun forCode(code: String): PrivacyStrings = when (code) {
            "ES" -> PrivacyStrings(
                title                = "Privacidad",
                currentStatus        = "ESTADO ACTUAL",
                privateProfile       = "Perfil privado",
                onlyYouMode          = "Solo tú",
                membersMode          = "Miembros",
                publicAlbumsSuffix   = "álbumes públicos",
                privatePhotosSuffix  = "fotos privadas",
                levelDescription     = "El nivel de perfil controla todo lo que hay debajo",
                stepProfile          = "PERFIL",
                stepAlbums           = "ÁLBUMES",
                stepPhotos           = "FOTOS",
                hierarchyHint        = "El nivel superior siempre tiene prioridad",
                sectionProfileMode   = "MODO DE PERFIL",
                soloTitle            = "Solo yo",
                soloDesc             = "Tu perfil, fotos y estadísticas son completamente privados. Nadie puede verte si no te invitan a un álbum.",
                membersTitle         = "Miembros de mis álbumes",
                membersDesc          = "Las personas que comparten álbumes contigo pueden ver tu perfil. Sigues controlando qué muestras.",
                defaultBadge         = "POR DEFECTO",
                warningText          = "Mientras tu perfil esté en modo privado, ningún álbum será visible aunque lo configures como público.",
                sectionWhatCanSee    = "QUÉ PUEDEN VER",
                photoAndName         = "Foto y nombre",
                alwaysVisibleFor     = "Siempre visible para miembros",
                always               = "SIEMPRE",
                publicPhotos         = "Mis fotos públicas",
                stats                = "Estadísticas",
                sectionAlbums        = "ÁLBUMES",
                whoCanInvite         = "¿Quién puede invitarme?",
                approveBeforeJoining = "Aprobar antes de unirme",
                approveDesc          = "Revisa las invitaciones antes de aceptarlas",
                sectionAlbumSummary  = "MIS ÁLBUMES — RESUMEN",
                albumPrivate         = "Privados",
                albumWithLink        = "Con enlace",
                albumPublic          = "Públicos",
                albumUnit            = "álbum",
                albumUnitPlural      = "álbumes",
                managePrivacy        = "Gestionar privacidad por álbum",
                saveChanges          = "GUARDAR CAMBIOS",
            )
            "FR" -> PrivacyStrings(
                title                = "Confidentialité",
                currentStatus        = "STATUT ACTUEL",
                privateProfile       = "Profil privé",
                onlyYouMode          = "Seulement vous",
                membersMode          = "Membres",
                publicAlbumsSuffix   = "albums publics",
                privatePhotosSuffix  = "photos privées",
                levelDescription     = "Le niveau de profil contrôle tout ce qui est en dessous",
                stepProfile          = "PROFIL",
                stepAlbums           = "ALBUMS",
                stepPhotos           = "PHOTOS",
                hierarchyHint        = "Le niveau supérieur a toujours la priorité",
                sectionProfileMode   = "MODE DE PROFIL",
                soloTitle            = "Moi uniquement",
                soloDesc             = "Votre profil, photos et statistiques sont complètement privés. Personne ne peut vous voir sans invitation.",
                membersTitle         = "Membres de mes albums",
                membersDesc          = "Les personnes qui partagent des albums avec vous peuvent voir votre profil. Vous contrôlez ce que vous montrez.",
                defaultBadge         = "PAR DÉFAUT",
                warningText          = "Tant que votre profil est en mode privé, aucun album ne sera visible même s'il est configuré comme public.",
                sectionWhatCanSee    = "CE QU'ILS PEUVENT VOIR",
                photoAndName         = "Photo et nom",
                alwaysVisibleFor     = "Toujours visible pour les membres",
                always               = "TOUJOURS",
                publicPhotos         = "Mes photos publiques",
                stats                = "Statistiques",
                sectionAlbums        = "ALBUMS",
                whoCanInvite         = "Qui peut m'inviter ?",
                approveBeforeJoining = "Approuver avant de rejoindre",
                approveDesc          = "Vérifiez les invitations avant de les accepter",
                sectionAlbumSummary  = "MES ALBUMS — RÉSUMÉ",
                albumPrivate         = "Privés",
                albumWithLink        = "Avec lien",
                albumPublic          = "Publics",
                albumUnit            = "album",
                albumUnitPlural      = "albums",
                managePrivacy        = "Gérer la confidentialité par album",
                saveChanges          = "ENREGISTRER",
            )
            "IT" -> PrivacyStrings(
                title                = "Privacy",
                currentStatus        = "STATO ATTUALE",
                privateProfile       = "Profilo privato",
                onlyYouMode          = "Solo tu",
                membersMode          = "Membri",
                publicAlbumsSuffix   = "album pubblici",
                privatePhotosSuffix  = "foto private",
                levelDescription     = "Il livello del profilo controlla tutto ciò che è sotto",
                stepProfile          = "PROFILO",
                stepAlbums           = "ALBUM",
                stepPhotos           = "FOTO",
                hierarchyHint        = "Il livello superiore ha sempre la priorità",
                sectionProfileMode   = "MODALITÀ PROFILO",
                soloTitle            = "Solo io",
                soloDesc             = "Il tuo profilo, foto e statistiche sono completamente privati. Nessuno può vederti senza invito.",
                membersTitle         = "Membri dei miei album",
                membersDesc          = "Le persone che condividono album con te possono vedere il tuo profilo. Controlli sempre cosa mostrare.",
                defaultBadge         = "PREDEFINITO",
                warningText          = "Finché il tuo profilo è in modalità privata, nessun album sarà visibile anche se configurato come pubblico.",
                sectionWhatCanSee    = "COSA POSSONO VEDERE",
                photoAndName         = "Foto e nome",
                alwaysVisibleFor     = "Sempre visibile per i membri",
                always               = "SEMPRE",
                publicPhotos         = "Le mie foto pubbliche",
                stats                = "Statistiche",
                sectionAlbums        = "ALBUM",
                whoCanInvite         = "Chi può invitarmi?",
                approveBeforeJoining = "Approva prima di unirmi",
                approveDesc          = "Controlla gli inviti prima di accettarli",
                sectionAlbumSummary  = "I MIEI ALBUM — RIEPILOGO",
                albumPrivate         = "Privati",
                albumWithLink        = "Con link",
                albumPublic          = "Pubblici",
                albumUnit            = "album",
                albumUnitPlural      = "album",
                managePrivacy        = "Gestisci privacy per album",
                saveChanges          = "SALVA MODIFICHE",
            )
            "ZH" -> PrivacyStrings(
                title                = "隐私",
                currentStatus        = "当前状态",
                privateProfile       = "私密资料",
                onlyYouMode          = "仅自己",
                membersMode          = "成员",
                publicAlbumsSuffix   = "个公开相册",
                privatePhotosSuffix  = "张私密照片",
                levelDescription     = "资料级别控制以下所有内容",
                stepProfile          = "资料",
                stepAlbums           = "相册",
                stepPhotos           = "照片",
                hierarchyHint        = "上级设置始终优先",
                sectionProfileMode   = "资料模式",
                soloTitle            = "仅自己",
                soloDesc             = "您的资料、照片和统计数据完全私密。没有邀请则无人可见。",
                membersTitle         = "我的相册成员",
                membersDesc          = "与您共享相册的人可以看到您的资料。您仍然控制显示内容。",
                defaultBadge         = "默认",
                warningText          = "只要您的资料处于私密模式，即使设置为公开，相册也不会显示。",
                sectionWhatCanSee    = "他们可以看到什么",
                photoAndName         = "头像和名字",
                alwaysVisibleFor     = "对成员始终可见",
                always               = "始终",
                publicPhotos         = "我的公开照片",
                stats                = "统计数据",
                sectionAlbums        = "相册",
                whoCanInvite         = "谁可以邀请我？",
                approveBeforeJoining = "加入前审批",
                approveDesc          = "接受邀请前先审核",
                sectionAlbumSummary  = "我的相册 — 概览",
                albumPrivate         = "私密",
                albumWithLink        = "链接共享",
                albumPublic          = "公开",
                albumUnit            = "个相册",
                albumUnitPlural      = "个相册",
                managePrivacy        = "按相册管理隐私",
                saveChanges          = "保存更改",
            )
            "JA" -> PrivacyStrings(
                title                = "プライバシー",
                currentStatus        = "現在の状態",
                privateProfile       = "プライベートプロフィール",
                onlyYouMode          = "自分のみ",
                membersMode          = "メンバー",
                publicAlbumsSuffix   = "件の公開アルバム",
                privatePhotosSuffix  = "枚のプライベート写真",
                levelDescription     = "プロフィールレベルがすべてを制御します",
                stepProfile          = "プロフィール",
                stepAlbums           = "アルバム",
                stepPhotos           = "写真",
                hierarchyHint        = "上位レベルが常に優先されます",
                sectionProfileMode   = "プロフィールモード",
                soloTitle            = "自分のみ",
                soloDesc             = "プロフィール、写真、統計はすべてプライベートです。招待なしでは誰も見ることができません。",
                membersTitle         = "マイアルバムのメンバー",
                membersDesc          = "アルバムを共有しているメンバーがプロフィールを見ることができます。表示内容はあなたが管理します。",
                defaultBadge         = "デフォルト",
                warningText          = "プロフィールがプライベートモードの間は、公開に設定しても、アルバムは表示されません。",
                sectionWhatCanSee    = "何が見られるか",
                photoAndName         = "写真と名前",
                alwaysVisibleFor     = "メンバーには常に表示",
                always               = "常時",
                publicPhotos         = "私の公開写真",
                stats                = "統計",
                sectionAlbums        = "アルバム",
                whoCanInvite         = "誰が招待できますか？",
                approveBeforeJoining = "参加前に承認",
                approveDesc          = "招待を承認する前に確認する",
                sectionAlbumSummary  = "マイアルバム — 概要",
                albumPrivate         = "プライベート",
                albumWithLink        = "リンク共有",
                albumPublic          = "公開",
                albumUnit            = "件のアルバム",
                albumUnitPlural      = "件のアルバム",
                managePrivacy        = "アルバム別にプライバシーを管理",
                saveChanges          = "変更を保存",
            )
            else -> PrivacyStrings( // EN
                title                = "Privacy",
                currentStatus        = "CURRENT STATUS",
                privateProfile       = "Private profile",
                onlyYouMode          = "Only you",
                membersMode          = "Members",
                publicAlbumsSuffix   = "public albums",
                privatePhotosSuffix  = "private photos",
                levelDescription     = "Profile level controls everything below",
                stepProfile          = "PROFILE",
                stepAlbums           = "ALBUMS",
                stepPhotos           = "PHOTOS",
                hierarchyHint        = "The top level always takes priority",
                sectionProfileMode   = "PROFILE MODE",
                soloTitle            = "Only me",
                soloDesc             = "Your profile, photos and stats are completely private. Nobody can see you without an album invitation.",
                membersTitle         = "My album members",
                membersDesc          = "People who share albums with you can see your profile. You still control what you show.",
                defaultBadge         = "DEFAULT",
                warningText          = "While your profile is in private mode, no album will be visible even if you configure it as public.",
                sectionWhatCanSee    = "WHAT THEY CAN SEE",
                photoAndName         = "Photo and name",
                alwaysVisibleFor     = "Always visible to members",
                always               = "ALWAYS",
                publicPhotos         = "My public photos",
                stats                = "Statistics",
                sectionAlbums        = "ALBUMS",
                whoCanInvite         = "Who can invite me?",
                approveBeforeJoining = "Approve before joining",
                approveDesc          = "Review invitations before accepting",
                sectionAlbumSummary  = "MY ALBUMS — SUMMARY",
                albumPrivate         = "Private",
                albumWithLink        = "Link-shared",
                albumPublic          = "Public",
                albumUnit            = "album",
                albumUnitPlural      = "albums",
                managePrivacy        = "Manage privacy per album",
                saveChanges          = "SAVE CHANGES",
            )
        }
    }
}
