package com.photogram.feature.story

internal data class StoryStrings(
    // Others'-story
    val closeStory: String,
    val sendReplyDesc: String,
    val heartReactDesc: String,
    val replySentPlaceholder: String,
    val replyDefaultPlaceholder: String,
    // Own-story: action bar
    val shareAction: String,
    val mentionAction: String,
    val moreAction: String,
    // Own-story: viewers sheet
    val seenBy: String,
    val noViewsYet: String,
    // Own-story: settings sheet
    val manageStory: String,
    val deleteStory: String,
    val archiveStory: String,
    val shareStory: String,
    val muteReplies: String,
    val unmuteReplies: String,
    val cancel: String,
    val deleteConfirmTitle: String,
    val deleteConfirmBody: String,
    val deleteConfirmAction: String,
    val archiveSheetTitle: String,
    val archiveSavedStories: String,
    val archiveCameraRoll: String,
    // Own-story: mentions sheet
    val tagPeople: String,
    val searchPeople: String,
    val done: String,
    // Own-story: share sheet
    val shareHeader: String,
    val copyLink: String,
    val linkCopied: String,
) {
    companion object {
        fun forCode(code: String): StoryStrings = when (code) {
            "ES" -> StoryStrings(
                closeStory              = "Cerrar historia",
                sendReplyDesc           = "Enviar respuesta",
                heartReactDesc          = "Reaccionar con corazón",
                replySentPlaceholder    = "¡Enviado!",
                replyDefaultPlaceholder = "Envía un mensaje...",
                shareAction             = "Compartir",
                mentionAction           = "Mencionar",
                moreAction              = "Más",
                seenBy                  = "VISTO POR",
                noViewsYet              = "Sin vistas aún",
                manageStory             = "HISTORIA",
                deleteStory             = "Eliminar historia",
                archiveStory            = "Archivar",
                shareStory              = "Compartir",
                muteReplies             = "Silenciar respuestas",
                unmuteReplies           = "Activar respuestas",
                cancel                  = "Cancelar",
                deleteConfirmTitle      = "¿Eliminar historia?",
                deleteConfirmBody       = "Esta historia se eliminará permanentemente.",
                deleteConfirmAction     = "Eliminar",
                archiveSheetTitle       = "GUARDAR HISTORIA EN",
                archiveSavedStories     = "Historias guardadas",
                archiveCameraRoll       = "Carrete de fotos",
                tagPeople               = "MENCIONAR PERSONAS",
                searchPeople            = "Buscar personas...",
                done                    = "Listo",
                shareHeader             = "COMPARTIR",
                copyLink                = "Copiar enlace",
                linkCopied              = "¡Enlace copiado!",
            )
            "FR" -> StoryStrings(
                closeStory              = "Fermer la story",
                sendReplyDesc           = "Envoyer la réponse",
                heartReactDesc          = "Réagir avec un cœur",
                replySentPlaceholder    = "Envoyé !",
                replyDefaultPlaceholder = "Envoyer un message...",
                shareAction             = "Partager",
                mentionAction           = "Mentionner",
                moreAction              = "Plus",
                seenBy                  = "VU PAR",
                noViewsYet              = "Pas encore de vues",
                manageStory             = "STORY",
                deleteStory             = "Supprimer la story",
                archiveStory            = "Archiver",
                shareStory              = "Partager",
                muteReplies             = "Désactiver les réponses",
                unmuteReplies           = "Réactiver les réponses",
                cancel                  = "Annuler",
                deleteConfirmTitle      = "Supprimer la story ?",
                deleteConfirmBody       = "Cette story sera supprimée définitivement.",
                deleteConfirmAction     = "Supprimer",
                archiveSheetTitle       = "ENREGISTRER DANS",
                archiveSavedStories     = "Stories enregistrées",
                archiveCameraRoll       = "Pellicule",
                tagPeople               = "IDENTIFIER DES PERSONNES",
                searchPeople            = "Rechercher...",
                done                    = "Terminé",
                shareHeader             = "PARTAGER",
                copyLink                = "Copier le lien",
                linkCopied              = "Lien copié !",
            )
            "IT" -> StoryStrings(
                closeStory              = "Chiudi storia",
                sendReplyDesc           = "Invia risposta",
                heartReactDesc          = "Reagisci con cuore",
                replySentPlaceholder    = "Inviato!",
                replyDefaultPlaceholder = "Invia un messaggio...",
                shareAction             = "Condividi",
                mentionAction           = "Menziona",
                moreAction              = "Altro",
                seenBy                  = "VISTO DA",
                noViewsYet              = "Nessuna visualizzazione",
                manageStory             = "STORIA",
                deleteStory             = "Elimina storia",
                archiveStory            = "Archivia",
                shareStory              = "Condividi",
                muteReplies             = "Silenzia risposte",
                unmuteReplies           = "Riattiva risposte",
                cancel                  = "Annulla",
                deleteConfirmTitle      = "Eliminare la storia?",
                deleteConfirmBody       = "Questa storia verrà eliminata definitivamente.",
                deleteConfirmAction     = "Elimina",
                archiveSheetTitle       = "SALVA STORIA IN",
                archiveSavedStories     = "Storie salvate",
                archiveCameraRoll       = "Rullino",
                tagPeople               = "MENZIONA PERSONE",
                searchPeople            = "Cerca persone...",
                done                    = "Fatto",
                shareHeader             = "CONDIVIDI",
                copyLink                = "Copia link",
                linkCopied              = "Link copiato!",
            )
            "ZH" -> StoryStrings(
                closeStory              = "关闭故事",
                sendReplyDesc           = "发送回复",
                heartReactDesc          = "用心形回应",
                replySentPlaceholder    = "已发送！",
                replyDefaultPlaceholder = "发送消息...",
                shareAction             = "分享",
                mentionAction           = "提及",
                moreAction              = "更多",
                seenBy                  = "已查看",
                noViewsYet              = "暂无查看",
                manageStory             = "故事",
                deleteStory             = "删除故事",
                archiveStory            = "归档",
                shareStory              = "分享",
                muteReplies             = "静音回复",
                unmuteReplies           = "取消静音回复",
                cancel                  = "取消",
                deleteConfirmTitle      = "删除故事？",
                deleteConfirmBody       = "此故事将被永久删除。",
                deleteConfirmAction     = "删除",
                archiveSheetTitle       = "保存故事到",
                archiveSavedStories     = "已保存的故事",
                archiveCameraRoll       = "相机胶卷",
                tagPeople               = "提及他人",
                searchPeople            = "搜索...",
                done                    = "完成",
                shareHeader             = "分享",
                copyLink                = "复制链接",
                linkCopied              = "链接已复制！",
            )
            "JA" -> StoryStrings(
                closeStory              = "ストーリーを閉じる",
                sendReplyDesc           = "返信を送る",
                heartReactDesc          = "ハートでリアクション",
                replySentPlaceholder    = "送信済み！",
                replyDefaultPlaceholder = "メッセージを送る...",
                shareAction             = "シェア",
                mentionAction           = "メンション",
                moreAction              = "その他",
                seenBy                  = "閲覧者",
                noViewsYet              = "まだ閲覧なし",
                manageStory             = "ストーリー",
                deleteStory             = "ストーリーを削除",
                archiveStory            = "アーカイブ",
                shareStory              = "シェア",
                muteReplies             = "返信をミュート",
                unmuteReplies           = "返信のミュートを解除",
                cancel                  = "キャンセル",
                deleteConfirmTitle      = "ストーリーを削除しますか？",
                deleteConfirmBody       = "このストーリーは完全に削除されます。",
                deleteConfirmAction     = "削除",
                archiveSheetTitle       = "保存先を選択",
                archiveSavedStories     = "保存済みストーリー",
                archiveCameraRoll       = "カメラロール",
                tagPeople               = "ユーザーをタグ付け",
                searchPeople            = "検索...",
                done                    = "完了",
                shareHeader             = "シェア",
                copyLink                = "リンクをコピー",
                linkCopied              = "コピーしました！",
            )
            else -> StoryStrings( // EN
                closeStory              = "Close story",
                sendReplyDesc           = "Send reply",
                heartReactDesc          = "React with heart",
                replySentPlaceholder    = "Sent!",
                replyDefaultPlaceholder = "Send a message...",
                shareAction             = "Share",
                mentionAction           = "Mention",
                moreAction              = "More",
                seenBy                  = "SEEN BY",
                noViewsYet              = "No views yet",
                manageStory             = "STORY",
                deleteStory             = "Delete story",
                archiveStory            = "Archive",
                shareStory              = "Share",
                muteReplies             = "Mute replies",
                unmuteReplies           = "Unmute replies",
                cancel                  = "Cancel",
                deleteConfirmTitle      = "Delete story?",
                deleteConfirmBody       = "This will permanently delete this story.",
                deleteConfirmAction     = "Delete",
                archiveSheetTitle       = "SAVE STORY TO",
                archiveSavedStories     = "Saved Stories",
                archiveCameraRoll       = "Camera Roll",
                tagPeople               = "TAG PEOPLE",
                searchPeople            = "Search people...",
                done                    = "Done",
                shareHeader             = "SHARE",
                copyLink                = "Copy link",
                linkCopied              = "Link copied!",
            )
        }
    }
}
