package com.photogram.feature.events

internal data class EventStrings(
    val itinerary: String,
    val guests: String,
    val guestsConfirmed: String,
    val viewFullList: String,
    val shareYourMoments: String,
    val captureEverySmile: String,
    val uploadPhotos: String,
    val editEventDesc: String,
    val closeDesc: String,
    val days: String,
    val hours: String,
    val min: String,
    val sec: String,
    val editEventTitle: String,
    val eventTitleField: String,
    val dateField: String,
    val locationField: String,
    val itinerarySection: String,
    val addItem: String,
    val guestsSection: String,
    val confirmedGuests: String,
    val saveChanges: String,
    val timeField: String,
    val nameField: String,
    val deleteDesc: String,
    val navEvent: String,
    val navGallery: String,
    val navChat: String,
    val navProfile: String,
) {
    companion object {
        fun forCode(code: String): EventStrings = when (code) {
            "ES" -> EventStrings(
                itinerary         = "ITINERARIO DEL EVENTO",
                guests            = "INVITADOS",
                guestsConfirmed   = "invitados confirmados",
                viewFullList      = "Ver lista completa",
                shareYourMoments  = "Comparte tus momentos",
                captureEverySmile = "Ayúdanos a capturar cada sonrisa...",
                uploadPhotos      = "SUBIR FOTOS",
                editEventDesc     = "Editar evento",
                closeDesc         = "Cerrar",
                days              = "DÍAS",
                hours             = "HORAS",
                min               = "MIN",
                sec               = "SEG",
                editEventTitle    = "Editar evento",
                eventTitleField   = "Título del evento",
                dateField         = "Fecha",
                locationField     = "Lugar",
                itinerarySection  = "ITINERARIO",
                addItem           = "Añadir elemento",
                guestsSection     = "INVITADOS",
                confirmedGuests   = "Invitados confirmados",
                saveChanges       = "GUARDAR CAMBIOS",
                timeField         = "Hora",
                nameField         = "Nombre",
                deleteDesc        = "Eliminar",
                navEvent          = "Evento",
                navGallery        = "Galería",
                navChat           = "Chat",
                navProfile        = "Perfil",
            )
            "FR" -> EventStrings(
                itinerary         = "PROGRAMME DE L'ÉVÉNEMENT",
                guests            = "INVITÉS",
                guestsConfirmed   = "invités confirmés",
                viewFullList      = "Voir la liste complète",
                shareYourMoments  = "Partagez vos moments",
                captureEverySmile = "Aidez-nous à capturer chaque sourire...",
                uploadPhotos      = "UPLOADER DES PHOTOS",
                editEventDesc     = "Modifier l'événement",
                closeDesc         = "Fermer",
                days              = "JOURS",
                hours             = "HEURES",
                min               = "MIN",
                sec               = "SEC",
                editEventTitle    = "Modifier l'événement",
                eventTitleField   = "Titre de l'événement",
                dateField         = "Date",
                locationField     = "Lieu",
                itinerarySection  = "PROGRAMME",
                addItem           = "Ajouter un élément",
                guestsSection     = "INVITÉS",
                confirmedGuests   = "Invités confirmés",
                saveChanges       = "ENREGISTRER",
                timeField         = "Heure",
                nameField         = "Nom",
                deleteDesc        = "Supprimer",
                navEvent          = "Événement",
                navGallery        = "Galerie",
                navChat           = "Chat",
                navProfile        = "Profil",
            )
            "IT" -> EventStrings(
                itinerary         = "PROGRAMMA DELL'EVENTO",
                guests            = "INVITATI",
                guestsConfirmed   = "invitati confermati",
                viewFullList      = "Vedi lista completa",
                shareYourMoments  = "Condividi i tuoi momenti",
                captureEverySmile = "Aiutaci a catturare ogni sorriso...",
                uploadPhotos      = "CARICA FOTO",
                editEventDesc     = "Modifica evento",
                closeDesc         = "Chiudi",
                days              = "GIORNI",
                hours             = "ORE",
                min               = "MIN",
                sec               = "SEC",
                editEventTitle    = "Modifica evento",
                eventTitleField   = "Titolo dell'evento",
                dateField         = "Data",
                locationField     = "Luogo",
                itinerarySection  = "PROGRAMMA",
                addItem           = "Aggiungi elemento",
                guestsSection     = "INVITATI",
                confirmedGuests   = "Invitati confermati",
                saveChanges       = "SALVA MODIFICHE",
                timeField         = "Ora",
                nameField         = "Nome",
                deleteDesc        = "Elimina",
                navEvent          = "Evento",
                navGallery        = "Galleria",
                navChat           = "Chat",
                navProfile        = "Profilo",
            )
            "ZH" -> EventStrings(
                itinerary         = "活动行程",
                guests            = "宾客",
                guestsConfirmed   = "位宾客已确认",
                viewFullList      = "查看完整列表",
                shareYourMoments  = "分享您的精彩时刻",
                captureEverySmile = "帮助我们捕捉每一个微笑...",
                uploadPhotos      = "上传照片",
                editEventDesc     = "编辑活动",
                closeDesc         = "关闭",
                days              = "天",
                hours             = "小时",
                min               = "分",
                sec               = "秒",
                editEventTitle    = "编辑活动",
                eventTitleField   = "活动标题",
                dateField         = "日期",
                locationField     = "地点",
                itinerarySection  = "行程",
                addItem           = "添加项目",
                guestsSection     = "宾客",
                confirmedGuests   = "已确认宾客",
                saveChanges       = "保存更改",
                timeField         = "时间",
                nameField         = "名称",
                deleteDesc        = "删除",
                navEvent          = "活动",
                navGallery        = "相册",
                navChat           = "聊天",
                navProfile        = "我的",
            )
            "JA" -> EventStrings(
                itinerary         = "イベントの行程",
                guests            = "ゲスト",
                guestsConfirmed   = "名のゲストが確認済み",
                viewFullList      = "全リストを見る",
                shareYourMoments  = "あなたのモーメントをシェア",
                captureEverySmile = "すべての笑顔を捉えましょう...",
                uploadPhotos      = "写真をアップロード",
                editEventDesc     = "イベントを編集",
                closeDesc         = "閉じる",
                days              = "日",
                hours             = "時間",
                min               = "分",
                sec               = "秒",
                editEventTitle    = "イベントを編集",
                eventTitleField   = "イベントタイトル",
                dateField         = "日付",
                locationField     = "場所",
                itinerarySection  = "行程",
                addItem           = "項目を追加",
                guestsSection     = "ゲスト",
                confirmedGuests   = "確認済みゲスト",
                saveChanges       = "変更を保存",
                timeField         = "時刻",
                nameField         = "名前",
                deleteDesc        = "削除",
                navEvent          = "イベント",
                navGallery        = "ギャラリー",
                navChat           = "チャット",
                navProfile        = "プロフィール",
            )
            else -> EventStrings( // EN
                itinerary         = "EVENT ITINERARY",
                guests            = "GUESTS",
                guestsConfirmed   = "guests confirmed",
                viewFullList      = "View full list",
                shareYourMoments  = "Share your moments",
                captureEverySmile = "Help us capture every smile...",
                uploadPhotos      = "UPLOAD PHOTOS",
                editEventDesc     = "Edit event",
                closeDesc         = "Close",
                days              = "DAYS",
                hours             = "HOURS",
                min               = "MIN",
                sec               = "SEC",
                editEventTitle    = "Edit event",
                eventTitleField   = "Event title",
                dateField         = "Date",
                locationField     = "Location",
                itinerarySection  = "ITINERARY",
                addItem           = "Add item",
                guestsSection     = "GUESTS",
                confirmedGuests   = "Confirmed guests",
                saveChanges       = "SAVE CHANGES",
                timeField         = "Time",
                nameField         = "Name",
                deleteDesc        = "Delete",
                navEvent          = "Event",
                navGallery        = "Gallery",
                navChat           = "Chat",
                navProfile        = "Profile",
            )
        }
    }
}
