package com.photogram.feature.auth

internal data class AuthStrings(
    val heroCreate: String,
    val heroSignIn: String,
    val orSignUpEmail: String,
    val orSignInEmail: String,
    val placeholderFullName: String,
    val placeholderEmail: String,
    val placeholderPassword: String,
    val showPassword: String,
    val hidePassword: String,
    val keepSignedIn: String,
    val ctaCreate: String,
    val ctaSignIn: String,
    val haveAccount: String,
    val noAccount: String,
    val signInLink: String,
    val createOneLink: String,
    val legalFooter: String,
    val checkEmail: String,
    val sentLink: String,
    val openLink: String,
    val languageTitle: String,
    val continueWithGoogle: String,
    val continueWithApple: String,
    val errorGoogleNotIntegrated: String,
    val errorAppleNotIntegrated: String,
) {
    companion object {
        fun forCode(code: String): AuthStrings = when (code) {
            "ES" -> AuthStrings(
                heroCreate = "Bienvenido a tu colección privada",
                heroSignIn = "Bienvenido a tu colección privada",
                orSignUpEmail = "— O REGÍSTRATE CON CORREO —",
                orSignInEmail = "— O INICIA SESIÓN CON CORREO —",
                placeholderFullName = "Nombre completo",
                placeholderEmail = "Correo electrónico",
                placeholderPassword = "Contraseña",
                showPassword = "Mostrar contraseña",
                hidePassword = "Ocultar contraseña",
                keepSignedIn = "Mantener sesión iniciada",
                ctaCreate = "Crear cuenta",
                ctaSignIn = "Iniciar sesión",
                haveAccount = "¿Ya tienes cuenta?",
                noAccount = "¿No tienes cuenta?",
                signInLink = "Inicia sesión",
                createOneLink = "Créala",
                legalFooter = "Al registrarte aceptas nuestros Términos y Política de Privacidad",
                checkEmail = "Revisa tu correo",
                sentLink = "Enviamos un enlace mágico a",
                openLink = "Abre el enlace del correo para iniciar sesión.\nPuedes cerrar esta pantalla.",
                languageTitle = "Idioma",
                continueWithGoogle = "Continuar con Google",
                continueWithApple = "Continuar con Apple",
                errorGoogleNotIntegrated = "Google: no integrado aún",
                errorAppleNotIntegrated = "Apple: no integrado aún",
            )
            "FR" -> AuthStrings(
                heroCreate = "Gardez chaque instant précieux.",
                heroSignIn = "Heureux de vous retrouver.",
                orSignUpEmail = "— OU S'INSCRIRE PAR E-MAIL —",
                orSignInEmail = "— OU SE CONNECTER PAR E-MAIL —",
                placeholderFullName = "Nom complet",
                placeholderEmail = "Adresse e-mail",
                placeholderPassword = "Mot de passe",
                showPassword = "Afficher le mot de passe",
                hidePassword = "Masquer le mot de passe",
                keepSignedIn = "Rester connecté",
                ctaCreate = "Créer un compte",
                ctaSignIn = "Se connecter",
                haveAccount = "Vous avez déjà un compte ?",
                noAccount = "Vous n'avez pas de compte ?",
                signInLink = "Se connecter",
                createOneLink = "En créer un",
                legalFooter = "En vous inscrivant, vous acceptez nos Conditions et notre Politique de confidentialité",
                checkEmail = "Vérifiez vos e-mails",
                sentLink = "Nous avons envoyé un lien magique à",
                openLink = "Ouvrez le lien dans l'e-mail pour vous connecter.\nVous pouvez fermer cet écran.",
                languageTitle = "Langue",
                continueWithGoogle = "Continuer avec Google",
                continueWithApple = "Continuer avec Apple",
                errorGoogleNotIntegrated = "Google : pas encore intégré",
                errorAppleNotIntegrated = "Apple : pas encore intégré",
            )
            "IT" -> AuthStrings(
                heroCreate = "Tieni vicino ogni momento.",
                heroSignIn = "Bentornato tra noi.",
                orSignUpEmail = "— O REGISTRATI CON EMAIL —",
                orSignInEmail = "— O ACCEDI CON EMAIL —",
                placeholderFullName = "Nome completo",
                placeholderEmail = "Indirizzo email",
                placeholderPassword = "Password",
                showPassword = "Mostra password",
                hidePassword = "Nascondi password",
                keepSignedIn = "Rimani connesso",
                ctaCreate = "Crea account",
                ctaSignIn = "Accedi",
                haveAccount = "Hai già un account?",
                noAccount = "Non hai un account?",
                signInLink = "Accedi",
                createOneLink = "Creane uno",
                legalFooter = "Registrandoti accetti i nostri Termini e la Privacy Policy",
                checkEmail = "Controlla la tua email",
                sentLink = "Abbiamo inviato un link magico a",
                openLink = "Apri il link nell'email per accedere.\nPuoi chiudere questa schermata.",
                languageTitle = "Lingua",
                continueWithGoogle = "Continua con Google",
                continueWithApple = "Continua con Apple",
                errorGoogleNotIntegrated = "Google: non ancora integrato",
                errorAppleNotIntegrated = "Apple: non ancora integrato",
            )
            "ZH" -> AuthStrings(
                heroCreate = "珍藏每一个珍贵瞬间。",
                heroSignIn = "很高兴再次见到你。",
                orSignUpEmail = "— 或通过邮箱注册 —",
                orSignInEmail = "— 或通过邮箱登录 —",
                placeholderFullName = "全名",
                placeholderEmail = "电子邮箱",
                placeholderPassword = "密码",
                showPassword = "显示密码",
                hidePassword = "隐藏密码",
                keepSignedIn = "保持登录状态",
                ctaCreate = "创建账户",
                ctaSignIn = "登录",
                haveAccount = "已有账户？",
                noAccount = "没有账户？",
                signInLink = "登录",
                createOneLink = "立即注册",
                legalFooter = "注册即表示您同意我们的条款和隐私政策",
                checkEmail = "查看您的邮箱",
                sentLink = "我们发送了一个魔法链接到",
                openLink = "打开邮件中的链接以登录。\n您可以关闭此屏幕。",
                languageTitle = "语言",
                continueWithGoogle = "使用 Google 继续",
                continueWithApple = "使用 Apple 继续",
                errorGoogleNotIntegrated = "Google：尚未集成",
                errorAppleNotIntegrated = "Apple：尚未集成",
            )
            "JA" -> AuthStrings(
                heroCreate = "大切な瞬間を、そばに。",
                heroSignIn = "おかえりなさい。",
                orSignUpEmail = "— またはメールで登録 —",
                orSignInEmail = "— またはメールでログイン —",
                placeholderFullName = "フルネーム",
                placeholderEmail = "メールアドレス",
                placeholderPassword = "パスワード",
                showPassword = "パスワードを表示",
                hidePassword = "パスワードを非表示",
                keepSignedIn = "ログイン状態を保持",
                ctaCreate = "アカウント作成",
                ctaSignIn = "ログイン",
                haveAccount = "すでにアカウントをお持ちですか？",
                noAccount = "アカウントをお持ちでないですか？",
                signInLink = "ログイン",
                createOneLink = "作成する",
                legalFooter = "登録することで利用規約とプライバシーポリシーに同意します",
                checkEmail = "メールを確認してください",
                sentLink = "マジックリンクを送信しました：",
                openLink = "メール内のリンクを開いてログインしてください。\nこの画面を閉じることができます。",
                languageTitle = "言語",
                continueWithGoogle = "Google で続ける",
                continueWithApple = "Apple で続ける",
                errorGoogleNotIntegrated = "Google：未統合",
                errorAppleNotIntegrated = "Apple：未統合",
            )
            else -> AuthStrings( // EN — default
                heroCreate = "Keep every moment close.",
                heroSignIn = "Good to have you back.",
                orSignUpEmail = "— OR SIGN UP WITH EMAIL —",
                orSignInEmail = "— OR SIGN IN WITH EMAIL —",
                placeholderFullName = "Full name",
                placeholderEmail = "Email address",
                placeholderPassword = "Password",
                showPassword = "Show password",
                hidePassword = "Hide password",
                keepSignedIn = "Keep me signed in",
                ctaCreate = "Create account",
                ctaSignIn = "Sign in",
                haveAccount = "Already have an account?",
                noAccount = "Don't have an account?",
                signInLink = "Sign in",
                createOneLink = "Create one",
                legalFooter = "By registering you agree to our Terms & Privacy Policy",
                checkEmail = "Check your email",
                sentLink = "We sent a magic link to",
                openLink = "Open the link in the email to sign in.\nYou can close this screen.",
                languageTitle = "Language",
                continueWithGoogle = "Continue with Google",
                continueWithApple = "Continue with Apple",
                errorGoogleNotIntegrated = "Google: not yet integrated",
                errorAppleNotIntegrated = "Apple: not yet integrated",
            )
        }
    }
}
