package com.photogram.feature.home

internal data class HomeStrings(
    val yourAlbums: String,
    val archived: String,
    val new: String,
    val premium: String,
    val relive: String,
    val create: String,
    val story: String,
    val shareWithGroup: String,
    val gallery: String,
    val cameraRoll: String,
    val album: String,
    val organizeShare: String,
    val navGallery: String,
    val navChat: String,
    val navProfile: String,
    val snackbarAlbumComingSoon: String,
    val snackbarFeaturedComingSoon: String,
    val snackbarSearchComingSoon: String,
) {
    companion object {
        fun forCode(code: String): HomeStrings = when (code) {
            "ES" -> HomeStrings(
                yourAlbums     = "TUS ÁLBUMES",
                archived       = "ARCHIVADOS",
                new            = "NUEVO",
                premium        = "Premium",
                relive         = "REVIVIR",
                create         = "CREAR",
                story          = "Historia",
                shareWithGroup = "Comparte un momento con tu grupo",
                gallery        = "Galería",
                cameraRoll     = "Carrete",
                album          = "Álbum",
                organizeShare  = "Organizar y compartir",
                navGallery     = "Galería",
                navChat        = "Chat",
                navProfile     = "Perfil",
                snackbarAlbumComingSoon     = "Detalle del álbum — próximamente",
                snackbarFeaturedComingSoon  = "Momentos destacados — próximamente",
                snackbarSearchComingSoon    = "Búsqueda — próximamente",
            )
            "FR" -> HomeStrings(
                yourAlbums     = "VOS ALBUMS",
                archived       = "ARCHIVÉS",
                new            = "NOUVEAU",
                premium        = "Premium",
                relive         = "REVIVRE",
                create         = "CRÉER",
                story          = "Story",
                shareWithGroup = "Partagez un moment avec votre groupe",
                gallery        = "Galerie",
                cameraRoll     = "Pellicule",
                album          = "Album",
                organizeShare  = "Organiser et partager",
                navGallery     = "Galerie",
                navChat        = "Chat",
                navProfile     = "Profil",
                snackbarAlbumComingSoon     = "Détail de l'album — bientôt disponible",
                snackbarFeaturedComingSoon  = "Souvenirs en vedette — bientôt disponible",
                snackbarSearchComingSoon    = "Recherche — bientôt disponible",
            )
            "IT" -> HomeStrings(
                yourAlbums     = "I TUOI ALBUM",
                archived       = "ARCHIVIATI",
                new            = "NUOVO",
                premium        = "Premium",
                relive         = "RIVIVERE",
                create         = "CREA",
                story          = "Storia",
                shareWithGroup = "Condividi un momento con il tuo gruppo",
                gallery        = "Galleria",
                cameraRoll     = "Rullino",
                album          = "Album",
                organizeShare  = "Organizza e condividi",
                navGallery     = "Galleria",
                navChat        = "Chat",
                navProfile     = "Profilo",
                snackbarAlbumComingSoon     = "Dettaglio album — prossimamente",
                snackbarFeaturedComingSoon  = "Memorie in evidenza — prossimamente",
                snackbarSearchComingSoon    = "Ricerca — prossimamente",
            )
            "ZH" -> HomeStrings(
                yourAlbums     = "您的相册",
                archived       = "已归档",
                new            = "新建",
                premium        = "高级版",
                relive         = "重温",
                create         = "创建",
                story          = "故事",
                shareWithGroup = "与您的群组分享一刻",
                gallery        = "相册",
                cameraRoll     = "胶卷",
                album          = "相册",
                organizeShare  = "整理与分享",
                navGallery     = "相册",
                navChat        = "聊天",
                navProfile     = "我的",
                snackbarAlbumComingSoon     = "相册详情 — 即将推出",
                snackbarFeaturedComingSoon  = "精选记忆 — 即将推出",
                snackbarSearchComingSoon    = "搜索 — 即将推出",
            )
            "JA" -> HomeStrings(
                yourAlbums     = "あなたのアルバム",
                archived       = "アーカイブ",
                new            = "新規",
                premium        = "プレミアム",
                relive         = "再体験",
                create         = "作成",
                story          = "ストーリー",
                shareWithGroup = "グループで瞬間をシェア",
                gallery        = "ギャラリー",
                cameraRoll     = "カメラロール",
                album          = "アルバム",
                organizeShare  = "整理してシェア",
                navGallery     = "ギャラリー",
                navChat        = "チャット",
                navProfile     = "プロフィール",
                snackbarAlbumComingSoon     = "アルバム詳細 — 近日公開",
                snackbarFeaturedComingSoon  = "注目のメモリー — 近日公開",
                snackbarSearchComingSoon    = "検索 — 近日公開",
            )
            else -> HomeStrings( // EN
                yourAlbums     = "YOUR ALBUMS",
                archived       = "ARCHIVED",
                new            = "NEW",
                premium        = "Premium",
                relive         = "RELIVE",
                create         = "CREATE",
                story          = "Story",
                shareWithGroup = "Share a moment with your group",
                gallery        = "Gallery",
                cameraRoll     = "Camera roll",
                album          = "Album",
                organizeShare  = "Organize & share",
                navGallery     = "Gallery",
                navChat        = "Chat",
                navProfile     = "Profile",
                snackbarAlbumComingSoon     = "Album detail — coming soon",
                snackbarFeaturedComingSoon  = "Featured memories — coming soon",
                snackbarSearchComingSoon    = "Search — coming soon",
            )
        }
    }
}
