package com.photogram.feature.notifications

internal data class NotificationsStrings(
    val title: String,
    val back: String,
    val filters: String,
    val today: String,
    val yesterday: String,
    val thisWeek: String,
    val advancedFilters: String,
    val close: String,
    val navHome: String,
    val navGallery: String,
    val navNotifications: String,
    val navProfile: String,
    val snackbarNotifComingSoon: String,
    val snackbarGalleryComingSoon: String,
) {
    companion object {
        fun forCode(code: String): NotificationsStrings = when (code) {
            "ES" -> NotificationsStrings(
                title             = "Notificaciones",
                back              = "Volver",
                filters           = "Filtros",
                today             = "Hoy",
                yesterday         = "Ayer",
                thisWeek          = "ESTA SEMANA",
                advancedFilters   = "Filtros avanzados — próximamente",
                close             = "Cerrar",
                navHome           = "Inicio",
                navGallery        = "Galería",
                navNotifications  = "Notificaciones",
                navProfile        = "Perfil",
                snackbarNotifComingSoon   = "Detalle de notificación — próximamente",
                snackbarGalleryComingSoon = "Galería — próximamente",
            )
            "FR" -> NotificationsStrings(
                title             = "Notifications",
                back              = "Retour",
                filters           = "Filtres",
                today             = "Aujourd'hui",
                yesterday         = "Hier",
                thisWeek          = "CETTE SEMAINE",
                advancedFilters   = "Filtres avancés — bientôt disponible",
                close             = "Fermer",
                navHome           = "Accueil",
                navGallery        = "Galerie",
                navNotifications  = "Notifications",
                navProfile        = "Profil",
                snackbarNotifComingSoon   = "Détail de notification — bientôt disponible",
                snackbarGalleryComingSoon = "Galerie — bientôt disponible",
            )
            "IT" -> NotificationsStrings(
                title             = "Notifiche",
                back              = "Indietro",
                filters           = "Filtri",
                today             = "Oggi",
                yesterday         = "Ieri",
                thisWeek          = "QUESTA SETTIMANA",
                advancedFilters   = "Filtri avanzati — prossimamente",
                close             = "Chiudi",
                navHome           = "Home",
                navGallery        = "Galleria",
                navNotifications  = "Notifiche",
                navProfile        = "Profilo",
                snackbarNotifComingSoon   = "Dettaglio notifica — prossimamente",
                snackbarGalleryComingSoon = "Galleria — prossimamente",
            )
            "ZH" -> NotificationsStrings(
                title             = "通知",
                back              = "返回",
                filters           = "筛选",
                today             = "今天",
                yesterday         = "昨天",
                thisWeek          = "本周",
                advancedFilters   = "高级筛选 — 即将推出",
                close             = "关闭",
                navHome           = "首页",
                navGallery        = "相册",
                navNotifications  = "通知",
                navProfile        = "我的",
                snackbarNotifComingSoon   = "通知详情 — 即将推出",
                snackbarGalleryComingSoon = "相册 — 即将推出",
            )
            "JA" -> NotificationsStrings(
                title             = "通知",
                back              = "戻る",
                filters           = "フィルター",
                today             = "今日",
                yesterday         = "昨日",
                thisWeek          = "今週",
                advancedFilters   = "高度なフィルター — 近日公開",
                close             = "閉じる",
                navHome           = "ホーム",
                navGallery        = "ギャラリー",
                navNotifications  = "通知",
                navProfile        = "プロフィール",
                snackbarNotifComingSoon   = "通知の詳細 — 近日公開",
                snackbarGalleryComingSoon = "ギャラリー — 近日公開",
            )
            else -> NotificationsStrings( // EN
                title             = "Notifications",
                back              = "Back",
                filters           = "Filters",
                today             = "Today",
                yesterday         = "Yesterday",
                thisWeek          = "THIS WEEK",
                advancedFilters   = "Advanced filters — coming soon",
                close             = "Close",
                navHome           = "Home",
                navGallery        = "Gallery",
                navNotifications  = "Notifications",
                navProfile        = "Profile",
                snackbarNotifComingSoon   = "Notification detail — coming soon",
                snackbarGalleryComingSoon = "Gallery — coming soon",
            )
        }
    }
}
