package com.photogram.feature.settings

internal data class EditProfileStrings(
    val title: String,
    val save: String,
    val changePhoto: String,
    val sectionInfo: String,
    val nameLabel: String,
    val namePlaceholder: String,
    val usernameLabel: String,
    val usernamePlaceholder: String,
    val sectionBio: String,
    val bioLabel: String,
    val bioPlaceholder: String,
    val sectionContact: String,
    val emailLabel: String,
    val saveButton: String,
) {
    companion object {
        fun forCode(code: String): EditProfileStrings = when (code) {
            "ES" -> EditProfileStrings(
                title               = "Editar perfil",
                save                = "Guardar",
                changePhoto         = "Cambiar foto",
                sectionInfo         = "INFORMACIÓN",
                nameLabel           = "Nombre",
                namePlaceholder     = "Tu nombre",
                usernameLabel       = "Usuario",
                usernamePlaceholder = "nombre.usuario",
                sectionBio          = "BIO",
                bioLabel            = "Bio",
                bioPlaceholder      = "Escribe algo sobre ti…",
                sectionContact      = "CONTACTO",
                emailLabel          = "Email",
                saveButton          = "GUARDAR",
            )
            "FR" -> EditProfileStrings(
                title               = "Modifier le profil",
                save                = "Enregistrer",
                changePhoto         = "Changer la photo",
                sectionInfo         = "INFORMATIONS",
                nameLabel           = "Nom",
                namePlaceholder     = "Votre nom",
                usernameLabel       = "Utilisateur",
                usernamePlaceholder = "nom.utilisateur",
                sectionBio          = "BIO",
                bioLabel            = "Bio",
                bioPlaceholder      = "Écrivez quelque chose sur vous…",
                sectionContact      = "CONTACT",
                emailLabel          = "Email",
                saveButton          = "ENREGISTRER",
            )
            "IT" -> EditProfileStrings(
                title               = "Modifica profilo",
                save                = "Salva",
                changePhoto         = "Cambia foto",
                sectionInfo         = "INFORMAZIONI",
                nameLabel           = "Nome",
                namePlaceholder     = "Il tuo nome",
                usernameLabel       = "Utente",
                usernamePlaceholder = "nome.utente",
                sectionBio          = "BIO",
                bioLabel            = "Bio",
                bioPlaceholder      = "Scrivi qualcosa su di te…",
                sectionContact      = "CONTATTO",
                emailLabel          = "Email",
                saveButton          = "SALVA",
            )
            "ZH" -> EditProfileStrings(
                title               = "编辑资料",
                save                = "保存",
                changePhoto         = "更换头像",
                sectionInfo         = "基本信息",
                nameLabel           = "姓名",
                namePlaceholder     = "您的姓名",
                usernameLabel       = "用户名",
                usernamePlaceholder = "用户.名称",
                sectionBio          = "简介",
                bioLabel            = "简介",
                bioPlaceholder      = "写点关于您自己的内容…",
                sectionContact      = "联系方式",
                emailLabel          = "邮箱",
                saveButton          = "保存",
            )
            "JA" -> EditProfileStrings(
                title               = "プロフィール編集",
                save                = "保存",
                changePhoto         = "写真を変更",
                sectionInfo         = "基本情報",
                nameLabel           = "名前",
                namePlaceholder     = "あなたの名前",
                usernameLabel       = "ユーザー名",
                usernamePlaceholder = "ユーザー.名前",
                sectionBio          = "プロフィール",
                bioLabel            = "プロフィール",
                bioPlaceholder      = "自己紹介を書いてください…",
                sectionContact      = "連絡先",
                emailLabel          = "メール",
                saveButton          = "保存",
            )
            else -> EditProfileStrings( // EN
                title               = "Edit profile",
                save                = "Save",
                changePhoto         = "Change photo",
                sectionInfo         = "INFORMATION",
                nameLabel           = "Name",
                namePlaceholder     = "Your name",
                usernameLabel       = "Username",
                usernamePlaceholder = "user.name",
                sectionBio          = "BIO",
                bioLabel            = "Bio",
                bioPlaceholder      = "Write something about you…",
                sectionContact      = "CONTACT",
                emailLabel          = "Email",
                saveButton          = "SAVE",
            )
        }
    }
}
