package com.photogram.feature.settings

internal data class NotificationsSettingsStrings(
    val title: String,
    val sectionGeneral: String,
    val newPhotos: String,
    val newPhotosSubtitle: String,
    val reactions: String,
    val reactionsSubtitle: String,
    val messages: String,
    val messagesSubtitle: String,
    val sectionAlbums: String,
    val invitations: String,
    val invitationsSubtitle: String,
    val updates: String,
    val updatesSubtitle: String,
    val sectionEvents: String,
    val reminders: String,
    val remindersSubtitle: String,
) {
    companion object {
        fun forCode(code: String): NotificationsSettingsStrings = when (code) {
            "ES" -> NotificationsSettingsStrings(
                title               = "Notificaciones",
                sectionGeneral      = "GENERAL",
                newPhotos           = "Nuevas fotos",
                newPhotosSubtitle   = "Cuando alguien sube al álbum",
                reactions           = "Reacciones",
                reactionsSubtitle   = "A tus fotos y publicaciones",
                messages            = "Mensajes",
                messagesSubtitle    = "Nuevos mensajes en álbumes",
                sectionAlbums       = "ÁLBUMES",
                invitations         = "Invitaciones",
                invitationsSubtitle = "Cuando te invitan a un álbum",
                updates             = "Actualizaciones",
                updatesSubtitle     = "Cambios en álbumes compartidos",
                sectionEvents       = "EVENTOS",
                reminders           = "Recordatorios",
                remindersSubtitle   = "Eventos y countdowns próximos",
            )
            "FR" -> NotificationsSettingsStrings(
                title               = "Notifications",
                sectionGeneral      = "GÉNÉRAL",
                newPhotos           = "Nouvelles photos",
                newPhotosSubtitle   = "Quand quelqu'un publie dans l'album",
                reactions           = "Réactions",
                reactionsSubtitle   = "À vos photos et publications",
                messages            = "Messages",
                messagesSubtitle    = "Nouveaux messages dans les albums",
                sectionAlbums       = "ALBUMS",
                invitations         = "Invitations",
                invitationsSubtitle = "Quand vous êtes invité dans un album",
                updates             = "Mises à jour",
                updatesSubtitle     = "Modifications dans les albums partagés",
                sectionEvents       = "ÉVÉNEMENTS",
                reminders           = "Rappels",
                remindersSubtitle   = "Événements et comptes à rebours à venir",
            )
            "IT" -> NotificationsSettingsStrings(
                title               = "Notifiche",
                sectionGeneral      = "GENERALE",
                newPhotos           = "Nuove foto",
                newPhotosSubtitle   = "Quando qualcuno carica sull'album",
                reactions           = "Reazioni",
                reactionsSubtitle   = "Alle tue foto e pubblicazioni",
                messages            = "Messaggi",
                messagesSubtitle    = "Nuovi messaggi negli album",
                sectionAlbums       = "ALBUM",
                invitations         = "Inviti",
                invitationsSubtitle = "Quando vieni invitato in un album",
                updates             = "Aggiornamenti",
                updatesSubtitle     = "Modifiche negli album condivisi",
                sectionEvents       = "EVENTI",
                reminders           = "Promemoria",
                remindersSubtitle   = "Prossimi eventi e countdown",
            )
            "ZH" -> NotificationsSettingsStrings(
                title               = "通知",
                sectionGeneral      = "通用",
                newPhotos           = "新照片",
                newPhotosSubtitle   = "当有人上传到相册时",
                reactions           = "反应",
                reactionsSubtitle   = "对您的照片和发布的反应",
                messages            = "消息",
                messagesSubtitle    = "相册中的新消息",
                sectionAlbums       = "相册",
                invitations         = "邀请",
                invitationsSubtitle = "当您被邀请加入相册时",
                updates             = "更新",
                updatesSubtitle     = "共享相册中的更改",
                sectionEvents       = "活动",
                reminders           = "提醒",
                remindersSubtitle   = "即将到来的活动和倒计时",
            )
            "JA" -> NotificationsSettingsStrings(
                title               = "通知",
                sectionGeneral      = "一般",
                newPhotos           = "新しい写真",
                newPhotosSubtitle   = "誰かがアルバムにアップロードしたとき",
                reactions           = "リアクション",
                reactionsSubtitle   = "あなたの写真と投稿へのリアクション",
                messages            = "メッセージ",
                messagesSubtitle    = "アルバムの新しいメッセージ",
                sectionAlbums       = "アルバム",
                invitations         = "招待",
                invitationsSubtitle = "アルバムに招待されたとき",
                updates             = "アップデート",
                updatesSubtitle     = "共有アルバムの変更",
                sectionEvents       = "イベント",
                reminders           = "リマインダー",
                remindersSubtitle   = "近日開催のイベントとカウントダウン",
            )
            else -> NotificationsSettingsStrings( // EN
                title               = "Notifications",
                sectionGeneral      = "GENERAL",
                newPhotos           = "New photos",
                newPhotosSubtitle   = "When someone uploads to the album",
                reactions           = "Reactions",
                reactionsSubtitle   = "To your photos and posts",
                messages            = "Messages",
                messagesSubtitle    = "New messages in albums",
                sectionAlbums       = "ALBUMS",
                invitations         = "Invitations",
                invitationsSubtitle = "When you're invited to an album",
                updates             = "Updates",
                updatesSubtitle     = "Changes in shared albums",
                sectionEvents       = "EVENTS",
                reminders           = "Reminders",
                remindersSubtitle   = "Upcoming events and countdowns",
            )
        }
    }
}
