package com.photogram.feature.settings

/**
 * Translations for all visible strings in SettingsScreen and LanguagePickerScreen.
 * Language codes are uppercase and match AuthStrings exactly: EN, ES, FR, IT, ZH, JA.
 */
internal data class SettingsStrings(
    // ── SettingsScreen ──────────────────────────────────────────────────────────
    val screenTitle: String,
    val sectionAccount: String,
    val itemPassword: String,
    val itemPrivacy: String,
    val sectionPreferences: String,
    val itemDarkMode: String,
    val itemLanguage: String,
    val itemNotifications: String,
    val sectionAlbums: String,
    val itemStorage: String,
    val storageOf: String,
    val storageUsed: String,
    val itemDownload: String,
    val buttonLogOut: String,
    val buttonEditProfile: String,
    // ── Dialogs ─────────────────────────────────────────────────────────────────
    val dialogLogOutTitle: String,
    val dialogLogOutBody: String,
    val dialogLogOutCancel: String,
    val dialogLogOutConfirm: String,
    val dialogDownloadTitle: String,
    val dialogDownloadBody: String,
    val dialogDownloadCancel: String,
    val dialogDownloadConfirm: String,
    // ── LanguagePickerScreen ─────────────────────────────────────────────────────
    val languageScreenTitle: String,
    val languageSectionLabel: String,
    val languageFooter: String,
) {
    companion object {
        fun forCode(code: String): SettingsStrings = when (code) {
            "ES" -> SettingsStrings(
                screenTitle           = "Ajustes",
                sectionAccount        = "CUENTA",
                itemPassword          = "Contraseña",
                itemPrivacy           = "Privacidad",
                sectionPreferences    = "PREFERENCIAS",
                itemDarkMode          = "Modo oscuro",
                itemLanguage          = "Idioma",
                itemNotifications     = "Notificaciones",
                sectionAlbums         = "ÁLBUMES",
                itemStorage           = "Almacenamiento",
                storageOf             = "de",
                storageUsed           = "usados",
                itemDownload          = "Descargar fotos",
                buttonLogOut          = "Cerrar sesión",
                buttonEditProfile     = "Editar\nperfil",
                dialogLogOutTitle     = "¿Cerrar sesión?",
                dialogLogOutBody      = "Se cerrará tu sesión en este dispositivo. Podrás volver a iniciarla cuando quieras.",
                dialogLogOutCancel    = "Cancelar",
                dialogLogOutConfirm   = "Cerrar sesión",
                dialogDownloadTitle   = "Descargar fotos",
                dialogDownloadBody    = "Se descargarán todas tus fotos al dispositivo. Esto puede tardar varios minutos.",
                dialogDownloadCancel  = "Cancelar",
                dialogDownloadConfirm = "Descargar",
                languageScreenTitle   = "Idioma",
                languageSectionLabel  = "IDIOMA",
                languageFooter        = "El cambio de idioma se aplicará en el próximo inicio.",
            )
            "FR" -> SettingsStrings(
                screenTitle           = "Paramètres",
                sectionAccount        = "COMPTE",
                itemPassword          = "Mot de passe",
                itemPrivacy           = "Confidentialité",
                sectionPreferences    = "PRÉFÉRENCES",
                itemDarkMode          = "Mode sombre",
                itemLanguage          = "Langue",
                itemNotifications     = "Notifications",
                sectionAlbums         = "ALBUMS",
                itemStorage           = "Stockage",
                storageOf             = "sur",
                storageUsed           = "utilisé",
                itemDownload          = "Télécharger les photos",
                buttonLogOut          = "Se déconnecter",
                buttonEditProfile     = "Modifier\nle profil",
                dialogLogOutTitle     = "Se déconnecter ?",
                dialogLogOutBody      = "Vous serez déconnecté de cet appareil. Vous pourrez vous reconnecter à tout moment.",
                dialogLogOutCancel    = "Annuler",
                dialogLogOutConfirm   = "Se déconnecter",
                dialogDownloadTitle   = "Télécharger les photos",
                dialogDownloadBody    = "Toutes vos photos seront téléchargées sur l'appareil. Cela peut prendre plusieurs minutes.",
                dialogDownloadCancel  = "Annuler",
                dialogDownloadConfirm = "Télécharger",
                languageScreenTitle   = "Langue",
                languageSectionLabel  = "LANGUE",
                languageFooter        = "Le changement de langue s'appliquera au prochain démarrage.",
            )
            "IT" -> SettingsStrings(
                screenTitle           = "Impostazioni",
                sectionAccount        = "ACCOUNT",
                itemPassword          = "Password",
                itemPrivacy           = "Privacy",
                sectionPreferences    = "PREFERENZE",
                itemDarkMode          = "Modalità scura",
                itemLanguage          = "Lingua",
                itemNotifications     = "Notifiche",
                sectionAlbums         = "ALBUM",
                itemStorage           = "Spazio",
                storageOf             = "su",
                storageUsed           = "usato",
                itemDownload          = "Scarica foto",
                buttonLogOut          = "Esci",
                buttonEditProfile     = "Modifica\nprofilo",
                dialogLogOutTitle     = "Uscire?",
                dialogLogOutBody      = "Verrai disconnesso su questo dispositivo. Puoi accedere di nuovo in qualsiasi momento.",
                dialogLogOutCancel    = "Annulla",
                dialogLogOutConfirm   = "Esci",
                dialogDownloadTitle   = "Scarica foto",
                dialogDownloadBody    = "Tutte le tue foto verranno scaricate sul dispositivo. Questa operazione potrebbe richiedere diversi minuti.",
                dialogDownloadCancel  = "Annulla",
                dialogDownloadConfirm = "Scarica",
                languageScreenTitle   = "Lingua",
                languageSectionLabel  = "LINGUA",
                languageFooter        = "Il cambio di lingua verrà applicato al prossimo avvio.",
            )
            "ZH" -> SettingsStrings(
                screenTitle           = "设置",
                sectionAccount        = "账户",
                itemPassword          = "密码",
                itemPrivacy           = "隐私",
                sectionPreferences    = "偏好设置",
                itemDarkMode          = "深色模式",
                itemLanguage          = "语言",
                itemNotifications     = "通知",
                sectionAlbums         = "相册",
                itemStorage           = "存储",
                storageOf             = "共",
                storageUsed           = "已使用",
                itemDownload          = "下载照片",
                buttonLogOut          = "退出登录",
                buttonEditProfile     = "编辑\n资料",
                dialogLogOutTitle     = "退出登录？",
                dialogLogOutBody      = "您将在此设备上退出登录，可以随时重新登录。",
                dialogLogOutCancel    = "取消",
                dialogLogOutConfirm   = "退出登录",
                dialogDownloadTitle   = "下载照片",
                dialogDownloadBody    = "所有照片将被下载到此设备，这可能需要几分钟时间。",
                dialogDownloadCancel  = "取消",
                dialogDownloadConfirm = "下载",
                languageScreenTitle   = "语言",
                languageSectionLabel  = "语言",
                languageFooter        = "语言更改将在下次启动时生效。",
            )
            "JA" -> SettingsStrings(
                screenTitle           = "設定",
                sectionAccount        = "アカウント",
                itemPassword          = "パスワード",
                itemPrivacy           = "プライバシー",
                sectionPreferences    = "環境設定",
                itemDarkMode          = "ダークモード",
                itemLanguage          = "言語",
                itemNotifications     = "通知",
                sectionAlbums         = "アルバム",
                itemStorage           = "ストレージ",
                storageOf             = "/",
                storageUsed           = "使用中",
                itemDownload          = "写真をダウンロード",
                buttonLogOut          = "ログアウト",
                buttonEditProfile     = "プロフィール\n編集",
                dialogLogOutTitle     = "ログアウトしますか？",
                dialogLogOutBody      = "このデバイスからログアウトします。いつでも再ログインできます。",
                dialogLogOutCancel    = "キャンセル",
                dialogLogOutConfirm   = "ログアウト",
                dialogDownloadTitle   = "写真をダウンロード",
                dialogDownloadBody    = "すべての写真がこのデバイスにダウンロードされます。数分かかる場合があります。",
                dialogDownloadCancel  = "キャンセル",
                dialogDownloadConfirm = "ダウンロード",
                languageScreenTitle   = "言語",
                languageSectionLabel  = "言語",
                languageFooter        = "言語の変更は次回起動時に適用されます。",
            )
            else -> SettingsStrings( // EN — default
                screenTitle           = "Settings",
                sectionAccount        = "ACCOUNT",
                itemPassword          = "Password",
                itemPrivacy           = "Privacy",
                sectionPreferences    = "PREFERENCES",
                itemDarkMode          = "Dark mode",
                itemLanguage          = "Language",
                itemNotifications     = "Notifications",
                sectionAlbums         = "ALBUMS",
                itemStorage           = "Storage",
                storageOf             = "of",
                storageUsed           = "used",
                itemDownload          = "Download photos",
                buttonLogOut          = "Log out",
                buttonEditProfile     = "Edit\nprofile",
                dialogLogOutTitle     = "Log out?",
                dialogLogOutBody      = "You will be signed out on this device. You can sign back in at any time.",
                dialogLogOutCancel    = "Cancel",
                dialogLogOutConfirm   = "Log out",
                dialogDownloadTitle   = "Download photos",
                dialogDownloadBody    = "All your photos will be downloaded to this device. This may take several minutes.",
                dialogDownloadCancel  = "Cancel",
                dialogDownloadConfirm = "Download",
                languageScreenTitle   = "Language",
                languageSectionLabel  = "LANGUAGE",
                languageFooter        = "Language change will apply on next launch.",
            )
        }
    }
}
